mkdir ..\bin
mkdir ..\bin\Plugins
mkdir ..\o\CRT
mkdir ..\o\FarPlus
mkdir ..\o\MailView
mkdir ..\o\MailView\MsgLib
mkdir ..\o\MailView\Plugins
mkdir ..\o\MailView\Plugins\Folder
mkdir ..\o\MailView\Plugins\oe_dbx
mkdir ..\o\MailView\Plugins\PKT
mkdir ..\o\MailView\Plugins\Squish
mkdir ..\o\MailView\Plugins\TheBat
mkdir ..\o\MailView\Plugins\Unix
