@echo off
mkdir ..\o

mkdir ..\o\appendall
mkdir ..\o\bcopy
mkdir ..\o\case
mkdir ..\o\charmap
mkdir ..\o\defbutton
mkdir ..\o\extviewersearch
mkdir ..\o\grabdialog
mkdir ..\o\logger
mkdir ..\o\macro
mkdir ..\o\openfile
mkdir ..\o\pasteselection
mkdir ..\o\pwd
mkdir ..\o\replace
mkdir ..\o\search
mkdir ..\o\sr
mkdir ..\o\undo
mkdir ..\bin
mkdir ..\bin\Formats
mkdir ..\bin\Formats\AppendAll
mkdir ..\bin\Formats\BCopy
mkdir ..\bin\Formats\Case
mkdir ..\bin\Formats\CharMap
mkdir ..\bin\Formats\DefButton
mkdir ..\bin\Formats\ExtViewerSearch
mkdir ..\bin\Formats\GrabDialog
mkdir ..\bin\Formats\Logger
mkdir ..\bin\Formats\Macro
mkdir ..\bin\Formats\OpenFile
mkdir ..\bin\Formats\PasteSelection
mkdir ..\bin\Formats\Pwd
mkdir ..\bin\Formats\Replace
mkdir ..\bin\Formats\Search
mkdir ..\bin\Formats\SR
mkdir ..\bin\Formats\Undo
