/*
    FARMail plugin for FAR Manager
    Copyright (C) 2002-2004 FARMail Group
    Copyright (C) 1999,2000 Serge Alexandrov

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/
enum {
MesPluginMenuTitle,
MesDiskMenuTitle,

MesOk,
MesCancel,
MesYes,
MesNo,

MesError,
MesNoMem,

MesBadCmdLine,

MesMailbox_Title,
MesMailbox_Name,
MesMailbox_UserName,
MesMailbox_EMail,
MesMailbox_Organization,
MesMailbox_DefaultChkBx,
MesMailbox_UseAuthChkBx,
MesMailbox_UseSSLChkBx,
MesMailbox_SMTP,
MesMailbox_SMTPServer,
MesMailbox_SMTPUser,
MesMailbox_SMTPPass,
MesMailbox_SMTPPort,
MesMailbox_POP3IMAP4Port,
MesMailbox_POP3,
MesMailbox_IMAP4,
MesMailbox_POP3IMAP4Server,
MesMailbox_POP3IMAP4Login,
MesMailbox_POP3IMAP4Password,
MesMailbox_AM_1,
MesMailbox_AM_2,
MesMailbox_UIDL_1,
MesMailbox_UIDL_2,
MesMailbox_UIDL_3,
MesMailbox_MinTOP_1,
MesMailbox_MinTOP_2,
MesMailbox_MinTOP_3,

MesMailbox_MissingFields,
MesMailbox_AlreadyExist,
MesMailbox_InvalidChars,

MesDeleteMailbox,
MesDeleteMailboxConfirm,

MesEmptyMailbox,
MesEmptyMailboxConfirm,

MesGetLogin_Title,
MesGetLogin_User,
MesGetLogin_Pass,

MesErrWinsock,
MesErrorBreak,

MesErrData,
MesErrConnection,
MesErrUser,
MesErrPass,
MesErrQuit,
MesErrDel,
MesErrReset,
MesErrStat,
MesErrList,
MesErrRetr,

MesDelete_Title,
MesDelete_Question,
MesDelete_DeleteBtn,
MesDelete_CancelBtn,

MesKeybar_Undel,
MesKeybar_Reconnect,
MesKeybar_QuickView,
MesKeybar_QuickEdit,
MesKeybar_Filter,
MesKeybar_Version,
MesKeybar_AdrBook,
MesKeybar_NewMailbox,
MesKeybar_FastCopy,
MesKeybar_FastMove,
MesKeybar_FastDelete,
MesKeybar_Status,

MesFastStat_POP3,
MesFastStat_IMAP4,

MesMailboxName_Panel,
MesServerName_Panel,
MesMessageName_Panel,
MesSizeName_Panel,
MesFromName_Panel,
MesDateName_Panel,
MesSubjName_Panel,

MesCopy_Title,
MesCopy_Message,
MesCopy_CopyBtn,

MesMove_Title,
MesMove_Message,
MesMove_MoveBtn,

MesCopy_AssignUniqueNamesChkBx,
MesCopy_NoInbox,

MesOverwrite_Title,
MesOverwrite_Filename,
MesOverwrite_Question,
MesOverwrite_YesBtn,
MesOverwrite_AllBtn,
MesOverwrite_SkipBtn,
MesOverwrite_SkipAllBtn,
MesOverwrite_ResumeBtn,

MesSMTP_421,
MesSMTP_450,
MesSMTP_451,
MesSMTP_452,
MesSMTP_500,
MesSMTP_501,
MesSMTP_502,
MesSMTP_503,
MesSMTP_504,
MesSMTP_550,
MesSMTP_551,
MesSMTP_552,
MesSMTP_553,
MesSMTP_554,
MesSMTP_DefaultError,
MesSMTP_ConnectionError,
MesSMTP_RecipientError,
MesSMTP_OpeningFileError,
MesSMTP_AUTHError,

MesSendDialog_Title,
MesSendDialog_MultiPartTitle,
MesSendDialog_From,
MesSendDialog_To,
MesSendDialog_CC,
MesSendDialog_BCC,
MesSendDialog_Subj,
MesSendDialog_SendAs,
MesSendDialog_SendAs_TextAsIs,
MesSendDialog_SendAs_TextBase64,
MesSendDialog_SendAs_AttachedFile,
MesSendDialog_SendAs_HtmlAsIs,
MesSendDialog_SendAs_HtmlBase64,
MesSendDialog_SendAs_Raw,
MesSendDialog_OriginalCharset,
MesSendDialog_EncodeTo,
MesSendDialog_OEM,
MesSendDialog_USASCII,
MesSendDialog_DoNotEncode,
//MesSendDialog_NoSuchEncoding,
MesSendDialog_AttachesBtn,
MesSendDialog_UserHeadersBtn,
MesSendDialog_AllBtn,
MesSendDialog_AnalizeAllBtn,

MesSelectMailbox_Title,

MesProgressSend_Title,
MesProgressReceive_Title,
MesProgressReceiveFast_Title,
MesProgress_Body,

MesRootPanelTitle,

MsgConnectSMTP,
MsgMailSMTP,
MsgRcptSMTP,
MsgDataSMTP,
MsgQuitSMTP,

MsgConnectPOP,
MsgListPOP,
MsgDelPOP,
MsgQuitPOP,
MsgResetPOP,

MesConfig_MainTitle,

MesConfig_Interface,
MesConfig_FilesDirectories,
MesConfig_Connection,
MesConfig_Encodings,
MesConfig_States,
MesConfig_Other,

MesConfig_AddToDisksMenuChkBx,
MesConfig_DisksMenuHotkey,
MesConfig_AddToPluginsMenu,
MesConfig_SelectPanel,
MesConfig_MailboxesPanel,
MesConfig_IMAP4FoldersPanel,
MesConfig_POP3MailboxPanel,
MesConfig_IMAP4MailboxPanel,
MesConfig_Mode,
MesConfig_ColumnTypes,
MesConfig_ColumnWidths,
MesConfig_StatusColumnTypes,
MesConfig_StatusColumnWidths,
MesConfig_FullScreenChkBx,

MesConfig_MsgFixedNameLength,
MesConfig_MsgExtension,
MesConfig_IncomingSubTitle,
MesConfig_AssignNewNameChkBx,
MesConfig_NameFormat,
MesConfig_UseInboxChkBx,
MesConfig_InboxFilename,
MesConfig_UseMsgDateChkBx,
MesConfig_OutgoingSubTitle,
MesConfig_SaveOutgoingChkBx,
MesConfig_OutgoingDirectory,
MesConfig_Outbox,
MesConfig_SaveOutgoingMsgIdChkBx,
MesConfig_MsgIdTemplate,

MesConfig_WSKTimeout1,
MesConfig_WSKTimeout2,
MesConfig_WriteLogChkBx,
MesConfig_IMAP4SubTitle,
MesConfig_QuickViewTitle1,
MesConfig_QuickViewBytes,
MesConfig_ResumeOnIMAP4ChkBx,
MesConfig_IMAP4Folders,
MesConfig_POP3SubTitle,
MesConfig_QuickViewTitle2,
MesConfig_QuickViewLines,
MesConfig_DisplayZeroSizeMsgsChkBx,
MesConfig_DisableTOP_and_LISTChkBx,

MesConfig_Charset,
MesConfig_UndefinedCharset,
MesConfig_Frequent,
MesConfig_FARTable,
MesConfig_Aditional,
MesConfig_Outgoing,
MesConfig_Incoming,

MesConfig_UseAttrHighlighting,
MesConfig_NewMessage,
MesConfig_ReadMessage,
MesConfig_MarkedMessage,
MesConfig_DeletedMessage,
MesConfig_Attr_R,
MesConfig_Attr_A,
MesConfig_Attr_H,
MesConfig_Attr_S,
MesConfig_Attr_C,
MesConfig_Attr_E,

MesConfig_UseCCChkBx,
MesConfig_SearchHeaderInfoChkBx,
MesConfig_ConfirmBinary,

MesConfirmBinary_Message,
MesConfirmBinary_Continue,

MesOldVer,

MesEditorMenu_Send,

MesErrIMAP_Connect,
MesErrIMAP_NO_BAD,
MesErrIMAPAuth,
MesErrIMAP_Cap,
MesErrNoResume,

MsgConnectIMAP,
MsgIMAPList,

MesIMAPPanelMailbox,
MesIMAPPanelFlags,
MesIMAPPanelMessages,
MesIMAPPanelRecent,
MesIMAPPanelUnseen,

MesAllInOne_Question,
MesAllInOne_YesBtn,
MesAllInOne_NoBtn,

MesCache_Loading,

MesErrOpenFile,
MesErrWriteFile,

MesConnect_RetrMsgHeaders,

MesCreateDir1,
MesCreateDir2,
MesDeleteDir1,
MesDeleteDir2,
MesRenameDir1,
MesRenameDir2,
MesCopyMsg1,
MesCopyMsg2,
MesMoveMsg1,
MesMoveMsg2,

MesAboutBox,

MesPluginEditor,
MesPluginConfig,
MesPluginHotkey,
MesPluginHotkeyDialogTitle,
MesPluginHotkeyDialogLabel,

MesDefKOICharset,
MesDefKOITable,
MesDefWINCharset,
MesDefWINTable,

MesHotkeyA,
MesHotkeyB,
MesHotkeyC,
MesHotkeyD,
MesHotkeyE,
MesHotkeyF,
MesHotkey1,
MesHotkey2,
MesHotkey3,
MesHotkey4,
MesHotkey5,
MesHotkey6,
MesHotkey7,
MesHotkey8,
MesHotkey9,
};
